# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d41e23d6f6dfd118afa282a7cbaa25be001313f643b73534f9e89e34da619fc70cb5b9af291901cb3e5c20e885eab9a0be11f5d12b2ba66ce8f40b328d0028a7

test:
  secret_key_base: 96980b868cc2c8b51ed7c37fa939bbc2a4afb9bb20c9064d0e15e946a937305314d6c19ed9b0044185c94fa6d926dff620beb2ee716f8e8f4627b2b6a145e70c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
